# Generated by Django 6.1 on 2026-08-29 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0018_alter_datasource_options_alter_region_options_and_more'),
        ('bustimes', '0023_note_m2m_on_delete_cascade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoptime',
            name='stop_code',
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='busstops.stoppoint'),
        ),
    ]
